<?php

namespace ContainerLkXCK61;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSorareApiServiceService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Service\SorareApiService' shared autowired service.
     *
     * @return \App\Service\SorareApiService
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Service'.\DIRECTORY_SEPARATOR.'SorareApiService.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Service'.\DIRECTORY_SEPARATOR.'SorareAuthService.php';

        $a = ($container->privates['.debug.http_client'] ?? $container->get_Debug_HttpClientService());

        return $container->privates['App\\Service\\SorareApiService'] = new \App\Service\SorareApiService($a, new \App\Service\SorareAuthService($a), $container->getEnv('SORARE_EMAIL'), $container->getEnv('SORARE_PASSWORD'), $container->getEnv('SORARE_API_KEY'));
    }
}
