<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerLkXCK61\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerLkXCK61/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerLkXCK61.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerLkXCK61\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerLkXCK61\App_KernelDevDebugContainer([
    'container.build_hash' => 'LkXCK61',
    'container.build_id' => '32a66f8c',
    'container.build_time' => 1691571364,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerLkXCK61');
